version: "3"
services:
  database:
    image: "postgres:latest"
    restart: always
    volumes:
        - ./docker-create-database:/docker-entrypoint-initdb.d
    environment:
        - POSTGRES_PASSWORD=Mobile@final
        - POSTGRES_DATABASE=mobile
    ports:
      - "5434:5432"
