# Generated by Django 3.2.4 on 2021-06-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id',
                 models.AutoField(editable=False,
                                  primary_key=True,
                                  serialize=False,
                                  unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id',
                 models.AutoField(editable=False,
                                  primary_key=True,
                                  serialize=False,
                                  unique=True)),
                ('name', models.CharField(max_length=50)),
                ('clorie', models.IntegerField()),
                ('potion', models.IntegerField()),
                ('level', models.IntegerField()),
                ('star_level', models.IntegerField()),
                ('prepare', models.TextField()),
                ('youtube_url', models.CharField(max_length=500)),
                ('category',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='mobile_api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id',
                 models.AutoField(editable=False,
                                  primary_key=True,
                                  serialize=False,
                                  unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id',
                 models.AutoField(editable=False,
                                  primary_key=True,
                                  serialize=False,
                                  unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteFood',
            fields=[
                ('id',
                 models.AutoField(editable=False,
                                  primary_key=True,
                                  serialize=False,
                                  unique=True)),
                ('food',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='mobile_api.food')),
                ('user',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='mobile_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id',
                 models.AutoField(editable=False,
                                  primary_key=True,
                                  serialize=False,
                                  unique=True)),
                ('content', models.TextField()),
                ('food',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='mobile_api.food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id',
                 models.AutoField(editable=False,
                                  primary_key=True,
                                  serialize=False,
                                  unique=True)),
                ('quantity', models.CharField(max_length=50)),
                ('food',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='mobile_api.food')),
                ('ingredient',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='mobile_api.ingredient')),
            ],
        ),
    ]
