# Generated by Django 3.2.4 on 2021-06-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0001_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
