# Generated by Django 3.2.5 on 2021-07-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0002_alter_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
