# Generated by Django 3.2.5 on 2021-07-20 23:52

from django.db import migrations, models
import mobile_api.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0003_add_image_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=mobile_api.utils.photo_path),
        ),
    ]
