# Generated by Django 3.2.5 on 2021-07-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0004_remove_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='mobile_api.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='clorie',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='potion',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='star_level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='youtube_url',
            field=models.CharField(default='0', max_length=500, null=True),
        ),
    ]
