# Generated by Django 3.2.5 on 2021-07-21 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0005_change_nullability'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cover_image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mobile_api.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='clorie',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='potion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='star_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='youtube_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
